# Generated by Django 5.2.3 on 2025-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
