# Generated by Django 5.2 on 2025-07-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_locacao_observacoes_veiculo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='imagem',
        ),
    ]
